### ISSUE TITLE
Impose limits on hostile mobs outside of PVP regions

### ISSUE THREAD

**Issue by mrcoffee1026** [TheBusyBiscuit/HotbarPets#13]
It would generally not be possible for players to attack each other outside of PVP on my server but we've found that the Hotbar Pets are afforded an exception and can attack and kill other players anywhere.  (My mod was vaporized by someone's Hotbar creeper pet, for example).  Can you impose limitations on these mobs that would cause them to adhere to worldguard limitations, treating them as "players' so to obey PVP restrictions?

**Comment by TheBusyBiscuit** [comment]
Give us a list of pets that need this change first.

**Comment by mrcoffee1026** [comment]
I think this would only need to apply to the hostile pets but am uncertain if all pets can harm other other players in some way... the Iron Golem pet - for instance.  If this can become hostile to other players when provoked I'd count that as well, same with the slime pet.  The ones I know of: spider, ghast, shulker, phantom, enderman, creeper, magma cube, blaze, zombie, ender dragon, wither and of the special mobs I believe the Eyamaz might also be able to harm other players but correct me if I'm wrong.

**Comment by TheBusyBiscuit** [comment]
Are you sure about that list?
I see no way of "preventing players to harm each other" with most of the pets you listed...

Spider: Gives yourself Jump-Boost
Phantom: Gives yourself Slow Falling
Enderman: Shoots an Ender Pearl
Magma Cube: Immunity to Lava
Blaze Pet: Immunity to Fire
Zombie: Allows you to eat Rotten Flesh without getting hunger
Wither: Makes you immune to attacks from a Wither.
Eyamaz: Only modifies drops

How? How can these pets be used to harm others in the first place??

Ghasts, Dragons and Shulkers shoot projectiles, but the Player is explicitly set as the shooter, so any decent protection plugin should be able to handle that.

That's why I asked you to make a list.

**Comment by mrcoffee1026** [comment]
If it's just the explosion from the creeper that can harm other players then that's all I would need it for.
